#! /usr/bin/env zsh
# mise description="debug kernel"
tmux ls | grep -q "kernel"
if [ $? -ne 0 ]; then
    echo "create session 'kernel'"
    tmux new -d -s kernel -n qemu
    tmux new-window -tkernel -n gdb
else
    echo "session 'kernel' has existed, exit"
    exit
fi

tmux send-keys -tkernel:qemu "qemu-system-riscv64 \
-machine virt \
-nographic \
-bios ../bootloader/rustsbi-qemu.bin \
-device loader,file=target/riscv64gc-unknown-none-elf/release/kernel,addr=0x80200000 \
-s -S" C-m

tmux send-keys -tkernel:gdb "riscv64-unknown-elf-gdb \
-ex 'file target/riscv64gc-unknown-none-elf/release/kernel' \
-ex 'set arch riscv:rv64' \
-ex 'target remote localhost:1234' " C-m

tmux attach-session -tkernel:gdb